version: '3'
services:
  tb-nutricional-database:
    image: postgres:17
    container_name: tb-nutricional-database
    environment:
      - POSTGRES_DB=tabela-nutricional
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    networks:
      - refeicoes-network
  tb-nutricional-cache:
    image: redis:7
    container_name: tb-nutricional-cache
    ports:
      - "6381:6379"
    networks:
      - refeicoes-network

  tb-nutricional-api:
    build: 
      context: .
    container_name: tb-nutricional-api
    ports:
      - "8000:8000"
    networks:
      - refeicoes-network
    depends_on:
      - tb-nutricional-cache
      - tb-nutricional-database

networks:
  refeicoes-network:
    external: true