from model.ingrediente import Ingrediente


ingredientes = [
                Ingrediente(nome="Macarrão", calorias=131.0,
                            proteinas=5.0, carboidratos=25.0, gorduras=1.1),
                Ingrediente(nome="Alho", calorias=149.0,
                            proteinas=6.4, carboidratos=33.1, gorduras=0.5),
                Ingrediente(nome="Óleo", calorias=884.0,
                            proteinas=0.0, carboidratos=0.0, gorduras=100.0),
                Ingrediente(nome="Sal", calorias=0.0, proteinas=0.0,
                            carboidratos=0.0, gorduras=0.0),
                Ingrediente(nome="Pimenta-do-reino", calorias=255.0,
                            proteinas=10.4, carboidratos=64.8, gorduras=3.3),
                Ingrediente(nome="Banana", calorias=89.0,
                            proteinas=1.1, carboidratos=22.8, gorduras=0.3),
                Ingrediente(nome="Ovo", calorias=155.0,
                            proteinas=13.0, carboidratos=1.1, gorduras=11.0),
                Ingrediente(nome="Aveia", calorias=389.0,
                            proteinas=16.9, carboidratos=66.3, gorduras=6.9),
                Ingrediente(nome="Canela", calorias=247.0,
                            proteinas=4.0, carboidratos=80.6, gorduras=1.2),
                Ingrediente(nome="Cenoura", calorias=41.0,
                            proteinas=0.9, carboidratos=9.6, gorduras=0.2),
                Ingrediente(nome="Tomate", calorias=18.0,
                            proteinas=0.9, carboidratos=3.9, gorduras=0.2),
                Ingrediente(nome="Cebola", calorias=40.0,
                            proteinas=1.1, carboidratos=9.3, gorduras=0.1),
                Ingrediente(nome="Grão-de-bico", calorias=164.0,
                            proteinas=8.9, carboidratos=27.4, gorduras=2.6),
                Ingrediente(nome="Cebola Roxa", calorias=32.0,
                            proteinas=1.0, carboidratos=7.4, gorduras=0.1),
                Ingrediente(nome="Azeite", calorias=884.0,
                            proteinas=0.0, carboidratos=0.0, gorduras=100.0),
                Ingrediente(nome="Limão", calorias=29.0,
                            proteinas=1.1, carboidratos=9.3, gorduras=0.3),
                Ingrediente(nome="Arroz", calorias=130.0,
                            proteinas=2.4, carboidratos=28.2, gorduras=0.3),
                Ingrediente(nome="Frango Desfiado", calorias=165.0,
                            proteinas=31.0, carboidratos=0.0, gorduras=3.6),
                Ingrediente(nome="Milho", calorias=96.0,
                            proteinas=3.4, carboidratos=21.0, gorduras=1.5),
                Ingrediente(nome="Ervilha", calorias=81.0,
                            proteinas=5.4, carboidratos=14.5, gorduras=0.4),
                Ingrediente(nome="Molho de Tomate", calorias=29.0,
                            proteinas=1.4, carboidratos=5.8, gorduras=0.2),
                Ingrediente(nome="Queijo Ralado", calorias=402.0,
                            proteinas=25.0, carboidratos=1.3, gorduras=33.3),
                Ingrediente(nome="Goma de Tapioca", calorias=358.0,
                            proteinas=0.2, carboidratos=88.7, gorduras=0.1),
                Ingrediente(nome="Queijo", calorias=402.0,
                            proteinas=25.0, carboidratos=1.3, gorduras=33.3),
                Ingrediente(nome="Orégano", calorias=306.0,
                            proteinas=9.0, carboidratos=64.7, gorduras=10.3),
                Ingrediente(nome="Água", calorias=0.0, proteinas=0.0,
                            carboidratos=0.0, gorduras=0.0),
                Ingrediente(nome="Tortilha Integral", calorias=218.0,
                            proteinas=5.8, carboidratos=40.0, gorduras=4.1),
                Ingrediente(nome="Alface", calorias=15.0,
                            proteinas=1.4, carboidratos=2.9, gorduras=0.2),
                Ingrediente(nome="Maionese Light", calorias=184.0,
                            proteinas=0.5, carboidratos=2.5, gorduras=19.8),
                Ingrediente(nome="Farinha de Trigo", calorias=364.0,
                            proteinas=10.3, carboidratos=76.3, gorduras=1.0),
                Ingrediente(nome="Açúcar", calorias=387.0,
                            proteinas=0.0, carboidratos=100.0, gorduras=0.0),
                Ingrediente(nome="Leite", calorias=42.0,
                            proteinas=3.4, carboidratos=5.0, gorduras=1.0),
                Ingrediente(nome="Fermento", calorias=105.0,
                            proteinas=5.5, carboidratos=10.5, gorduras=1.5),
                Ingrediente(nome="Óleo para Fritar", calorias=884.0,
                            proteinas=0.0, carboidratos=0.0, gorduras=100.0),
                Ingrediente(nome="Abacate", calorias=160.0,
                            proteinas=2.0, carboidratos=9.0, gorduras=15.0),
                Ingrediente(nome="Abóbora", calorias=26.0,
                            proteinas=1.0, carboidratos=6.5, gorduras=0.1),
                Ingrediente(nome="Gengibre", calorias=80.0,
                            proteinas=1.8, carboidratos=17.8, gorduras=0.8),
                Ingrediente(nome="Tortilha", calorias=218.0,
                            proteinas=5.8, carboidratos=40.0, gorduras=4.1),
                Ingrediente(nome="Pepino", calorias=16.0,
                            proteinas=0.7, carboidratos=3.6, gorduras=0.1),
                Ingrediente(nome="Quinoa", calorias=120.0,
                            proteinas=4.4, carboidratos=21.3, gorduras=1.9),
                Ingrediente(nome="Farinha de Milho", calorias=365.0,
                            proteinas=9.4, carboidratos=76.9, gorduras=3.8),
                Ingrediente(nome="Arroz Arbóreo", calorias=357.0,
                            proteinas=6.8, carboidratos=78.9, gorduras=0.6),
                Ingrediente(nome="Caldo de Galinha", calorias=15.0,
                            proteinas=1.5, carboidratos=0.5, gorduras=0.5),
                Ingrediente(nome="Vinho Branco", calorias=82.0,
                            proteinas=0.1, carboidratos=2.6, gorduras=0.0),
                Ingrediente(nome="Polvilho Azedo", calorias=358.0,
                            proteinas=0.7, carboidratos=88.0, gorduras=0.1),
                Ingrediente(nome="Queijo Meia Cura", calorias=356.0,
                            proteinas=24.0, carboidratos=1.0, gorduras=28.0),
                Ingrediente(nome="Tofu", calorias=76.0,
                            proteinas=8.0, carboidratos=1.9, gorduras=4.8),
                Ingrediente(nome="Pimentão", calorias=31.0,
                            proteinas=1.0, carboidratos=6.0, gorduras=0.3),
                Ingrediente(nome="Molho Shoyu", calorias=53.0,
                            proteinas=8.1, carboidratos=4.9, gorduras=0.6),
                Ingrediente(nome="Coentro", calorias=23.0,
                            proteinas=2.1, carboidratos=3.7, gorduras=0.5),
                Ingrediente(nome="Cominho", calorias=375.0,
                            proteinas=17.8, carboidratos=44.2, gorduras=22.3),
                Ingrediente(nome="Lentilha", calorias=116.0,
                            proteinas=9.0, carboidratos=20.1, gorduras=0.4),
                Ingrediente(nome="Manteiga", calorias=717.0,
                            proteinas=0.5, carboidratos=0.1, gorduras=81.1),
                Ingrediente(nome="Chocolate em Pó", calorias=228.0,
                            proteinas=19.6, carboidratos=57.9, gorduras=22.2),
                Ingrediente(nome="Leite Condensado", calorias=321.0,
                            proteinas=7.9, carboidratos=54.5, gorduras=8.7),
                Ingrediente(nome="Granulado", calorias=430.0,
                            proteinas=3.6, carboidratos=80.0, gorduras=14.0)
            ]